config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  resources :cars
  # get :car  
  root "cars#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/car.rb
class Car < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/cars_controller.rb
class CarsController < ApplicationController
        def index
            @cars = Car.all
        end

        def edit
            @car = Car.find(params[:id])
            
        end

        def show
            @car = Car.find(params[:id])
        end

        def new
            @car = Car.new
        end

        def create
            @car = Car.new(car_params)
            if  @car.save
                redirect_to @car
            else
                render :new , status: unprocessable_entity
            end
        end

        def update
                @car = Car.find(params[:id])
                if @car.save
                    redirect_to @car
                else
                    render :edit ,status: unprocessable_entity
                end
        end

        def destroy
            @car = Car.find(params[:id])
            @car.destroy    
            redirect_to root_path , status: :see_other
        
        end

        private
        def car_params
                params.require(:car).permit(:name ,:buy_year , :number_plate , :color)             
        end
    
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cars_helper.rb
module CarsHelper
end

app/views/cars/_form.erb
<%= form_with model: car do |com|%>

<form>
  <div class="mb-3">
    <label for="exampleInputEmail1" class="form-label"><b> <%= com.label :name%></b></label>
       
    <input class="form-control"  <%= com.text_field :name %>>
  <% car.errors.full_messages_for(:name).each do |message|%>
        <% massage %>
        <% end %>
  </div>
  <div class="mb-3">
    <label for="exampleInputPassword1" class="form-label">  <%= com.label :buy_year %></label>
    <input  class="form-control" <%= com.text_field :buy_year %>>
     <% car.errors.full_messages_for(:buy_year).each do |message|%>
        <% message %>
        <% end %>
  </div>

   <div class="mb-3">
    <label for="exampleInputPassword1" class="form-label">  <%= com.label :number_plate %></label>
    <input  class="form-control" <%= com.text_field :number_plate %>>
     <% car.errors.full_messages_for(:number_plate).each do |message|%>
        <% message %>
        <% end %>
  </div>
 
    <div class="mb-3">
    <label for="exampleInputPassword1" class="form-label">  <%= com.label :color %></label>
    <input  class="form-control" <%= com.text_field :color %>>
     <% car.errors.full_messages_for(:color).each do |message|%>
        <% message %>
        <% end %>
  </div>

  <button type="submit" class="btn btn-primary"><%= com.submit %></button>
<% end %>

</form>

app/views/cars/edit.erb
<h1>this is a edit method</h1>

<%= render "form", car: @car %>
<%= link_to "show" , car_path , class: "btn btn-warning"%>

app/views/cars/index.erb
 <h1>Hello index<h2>

<table class = "table  table-hover  table-bordered border-primary table align-middle">
    <thead class = "table-dark">
        <tr>
            <th>Name:</th>
            <th>Buy_year:</th>
            <th>Number_plate:</th>
            <th>Color:</th>
        </tr>
    </thead>

    <% @cars.each do |car| %>

    <tbody class = ".table-striped">
        <tr>
            <td><%= car.name %></td>
            <td><%= car.buy_year%></td>
            <td><%= car.number_plate%></td>
            <td><%= car.color %></td>
            <td><%= link_to "Edit", edit_car_path(car) ,class:"btn btn-info"%></td>
            <td><%= link_to "show" , car_path(car) , class:"btn btn-warning" %></td>
            <td><%= link_to "destroy" , car_path(car), data:{turbo_method: :delete ,turbo_confirm: "Are You Sure? "} ,class:"btn btn-danger"%></td>
        </tr>
    </tbody>
    <% end %>

</table>

 <%= link_to "Enter New Car " , new_car_path , class:"btn btn-secondary"%>

app/views/cars/new.erb
<h1>this is a new method</h1>

<%= render "form" , car: @car %>

app/views/cars/show.erb
<h1>This is Show page</h1>

<%=  render "form" , car: @car %>

<%= link_to "Edit" , edit_car_path , class:"btn btn-info" %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Shop</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" 
      integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <%= javascript_importmap_tags %>
  </head>

  <body>
  
    <%= yield %>
  </body>
</html>